### ISSUE TITLE
Python is exiting with error status 1 : Permissions Error

### ISSUE THREAD

**Issue by randomeleven** [AAbouZaid/procCheck-telegraf-influxdb#1]
I am getting the following erro:

`E! ERROR in input [inputs.exec]: Errors encountered: [exec: exit status 1 for command '/usr/lib/telegraf/scripts/proccheck/procCheck.py']`

Appears to be a permissions error, since the procCheck.py code is trying to access `/proc` folder but doesn't have enough permissions as it's running as telegraf user.

Can you confirm/comment?

**Comment by aabouzaid** [comment]
Hi @randomeleven 
Could you please give more info about the OS, Telegraf, Python, and if you can run it directly form command line? With root and with Telegraf user?

Most probably it will not run with Python 3!

**Comment by aabouzaid** [comment]
Now it should work fine with py3, just in case this was the issue, try to pull latest version again :-)

**Comment by randomeleven** [comment]
@AAbouZaid 
OS:  Debian 8
Telegraf: v1.1.1
Python: 2.7
 - I can run it directly from command line (as root) and it's running as expected (outputs influx formated data)
- Can't seem to run it as telegraf user; `su-u telegraf "python procCheck.py"` returns nothing at all.

**Comment by aabouzaid** [comment]
Since telegraf user has a "/bin/false" shell, you should select the shell in `su` command.
So it should be something like this:
```
su - telegraf -s /bin/bash -c "python /usr/lib/telegraf/scripts/proccheck/procCheck.py"
```

On the other hand, I did check `/proc` permission in Debian 8, and Ubuntu use the same permissions.
So first thing I will check if `/usr/lib/telegraf/scripts/proccheck/procCheck.py` has execution permission or not?

**Comment by randomeleven** [comment]
It didn't have permission. This was the problem, now it's executing. Thank you

**Comment by randomeleven** [comment]
I have another issue now where kapacitor alerts are not working for some reason.

I used the same TICK script to log data. But can't seem to be able to trigger it.



I can verify that kapacitor is subscribed to influxdb by the command `show subscriprions`:

```

name: _internal
retention_policy name                                           mode destinations
---------------- ----                                           ---- ------------
monitor          kapacitor-f699a9a8-3d31-426e-bb9e-291bfc99ee19 ANY  [http://localhost:9092]


name: otherDB
retention_policy name                                           mode destinations
---------------- ----                                           ---- ------------
default          kapacitor-f699a9a8-3d31-426e-bb9e-291bfc99ee19 ANY  [http://localhost:9092]


name: telegraf
retention_policy name                                           mode destinations
---------------- ----                                           ---- ------------
default          kapacitor-f699a9a8-3d31-426e-bb9e-291bfc99ee19 ANY  [http://localhost:9092]


name: kapacitor_example
retention_policy name                                           mode destinations
---------------- ----                                           ---- ------------
autogen          kapacitor-f699a9a8-3d31-426e-bb9e-291bfc99ee19 ANY  [http://localhost:9092]
```



This is output from  kapacitor show `kapacitor_proccheck.tick`


```

ID: kapacitor_proccheck
Error:
Template:
Type: batch
Status: enabled
Executing: true
Created: 07 Mar 17 06:32 UTC
Modified: 12 Mar 17 10:14 UTC
LastEnabled: 12 Mar 17 10:14 UTC
Databases Retention Policies: ["kapacitor_example"."autogen"]
TICKscript:
batch
    // Counting will work fine for any column, since "count" just counts number of rows.
    // So the column "process_name" itself is not important here.
    |query('''
        SELECT count("process_name") as query_value
        FROM "MY_DB"."MY_RP"."procCheck"
        WHERE "process_name" = 'my_process'
    ''')
        .period(2m)
        .every(1m)
        .fill('null')
        .groupBy(time(1m), 'process_name', 'host')

    |deadman(0.0, 1m)
        // Alert title.
        .id('Monitored processes - {{ index .Tags "process_name" }}')

        // Alert body.
        .message('Server:{{ index .Tags "host" }}|Process {{ index .Tags "process_name" }} STOPPED!')

        // Send notification when state changes only.
        .stateChangesOnly()
        
        .log('/tmp/kapacitor_procscheck.log')

DOT:
digraph kapacitor_proccheck {
graph [throughput="0.00 batches/s"];

query1 [avg_exec_time_ns="0s" batches_queried="0" points_queried="0" query_errors="0" ];
query1 -> noop3 [processed="0"];

noop3 [avg_exec_time_ns="0s" ];

stats2 [avg_exec_time_ns="15.197µs" ];
stats2 -> derivative4 [processed="7"];

derivative4 [avg_exec_time_ns="0s" ];
derivative4 -> alert5 [processed="6"];

alert5 [alerts_triggered="0" avg_exec_time_ns="0s" crits_triggered="0" infos_triggered="0" oks_triggered="0" warns_triggered="0" ];
}


```


Why is the Query executed 0 times?
Can you please direct me to where the problem is ?

**Comment by aabouzaid** [comment]
This script uses `batch` not `stream`, so it doesn't rely on `subscriprions`. It will query InfluxDB. every time it works.

I'd suggest to check Kapacitord error log (default path in Ubuntu is /var/log/kapacitor/kapacitord.err) to see if there are any errors during running the script.
